### ISSUE TITLE
[Suggestion] UI workflow 

### ISSUE THREAD

**Issue by eltiel** [DaGooseYT/EncodeGUI#1]
First of all, thank you for this brilliant piece of software. It greatly simplifies encoding, especially when attempting to do stuff like upscaling and interpolation. It just works.

I do have some suggestions though, if you don't mind:

1. A popup after every "Add Job" gets tired after trying to add multiple items into the batch. Perhaps the notification can be just a text-change somewhere in the main window?
2. After input file is selected, can the output filename be defaulted into something that dynamically follows the input filename? I had this issue where for example, I added FileA as input, and named the output as FileA in a different folder. When I added FileB as another input, the output remained as FileA - this could lead to me overriding the FileA output if I forget to change the output path.

**Comment by DaGooseYT** [comment]
> First of all, thank you for this brilliant piece of software.

You're welcome!

> 1. A popup after every "Add Job" gets tired after trying to add multiple items into the batch. Perhaps the notification can be just a text-change somewhere in the main window?

I agree with this, however, the message box notification is in place so that the user doesn't add jabs too quickly (i.e. spamming the "Add Job" button) which in turn could cause problems. I can see what can be done for an alternative, but so far the message box notification is the best implementation.

> 2. After input file is selected, can the output filename be defaulted into something that dynamically follows the input filename? I had this issue where for example, I added FileA as input, and named the output as FileA in a different folder. When I added FileB as another input, the output remained as FileA - this could lead to me overriding the FileA output if I forget to change the output path.

This can be easily fixed. I'll add it to the next update.

**Comment by DaGooseYT** [comment]
Automatic output file path/name generation is now available in v1.0.7. Closing...
