### ISSUE TITLE
Upscaling GPU device selection and Dual GPU Processing

### ISSUE THREAD

**Issue by Cerlancism** [DaGooseYT/EncodeGUI#11]
One possible bug when selecting upscaling GPU:
When upscaling is enabled, it is always using the GPU stated on the Window title instead of the selected one.

Also stating some observations on Dual GPU processing:
If Dual GPU processing is enabled with GPUs of different speeds, the faster one is always waiting for the slower one to finish.

**Comment by DaGooseYT** [comment]
> When upscaling is enabled, it is always using the GPU stated on the Window title instead of the selected one.

What is your GPU appearing in the title versus the options you have when selecting a GPU?
Again, I say this all the time **without a log file and more details about your problem, I can’t help you.**

> If Dual GPU processing is enabled with GPUs of different speeds, the faster one is always waiting for the slower one to finish.

This is not an issue or bug. Two upscaling processes are initiated with the Dual GPU function. One GPU does the odd frames and the other one does the even ones. The even and odd frames must be rendered at the same speed for synchronization. Therefore, if using different GPUs, the entire process must slow down to the slowest GPU selected. 
Please only use similar speed GPUs when using the Dual GPU function.

**Comment by Cerlancism** [comment]
I apologize for missing out the submission instructions. Perhaps an issue template could further provide the instructions.

> When upscaling is enabled, it is always using the GPU stated on the Window title instead of the selected one.  

I have resolved the issue. I have set the preferred graphics processor to integrated graphics in the Nvidia control panel, reverting it back to auto resolves this problem. I did this to save power as the Nvidia GPU still able to work in places such as when using nvenc, as well as the when enabling the upscaling dual GPU processing.
![image](https://user-images.githubusercontent.com/28769707/216787368-3b87084a-6c56-47a7-8fd7-9ec1df98d309.png)

Thanks for the explanation for the dual GPU processing behavior. 

Attached logs for further reference. Excuse my old hardware, still works to some extends though.
[job-0352555.zip](https://github.com/DaGooseYT/EncodeGUI/files/10609530/job-0352555.zip)

• CPU: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
• GPU: Intel(R) HD Graphics 530 GPU, NVIDIA GeForce GTX 950M
• RAM: 16GB
• OS: Windows 11

**Comment by DaGooseYT** [comment]
Directions for submitting a proper issue/bug report are on the EncodeGUI/FrameGUI support page: https://encodegui.com/support.html, mitigating the need for an "issue template". The directions to fix your problem were also there as the first common fix option.
Regardless, i'm happy to hear that your issue was resolved.
