### ISSUE TITLE
DTS 5.1 to Opus Stereo downmix...

### ISSUE THREAD

**Issue by krab** [DaGooseYT/EncodeGUI#13]
Doesn't work?

I tried to compact DTS 5.1 @ 1509 Kbps into opus @ 320 Kbps stereo (downmix option enabled).

```
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (dts (dca) -> opus (libopus))
  Stream #1:2 -> #0:2 (dts (dca) -> opus (libopus))
  Stream #1:3 -> #0:3 (dts (dca) -> opus (libopus))
  Stream #1:4 -> #0:4 (dts (dca) -> opus (libopus))
  Stream #1:5 -> #0:5 (dts (dca) -> opus (libopus))
  Stream #1:6 -> #0:6 (dts (dca) -> opus (libopus))
  Stream #1:7 -> #0:7 (dts (dca) -> opus (libopus))
  Stream #1:8 -> #0:8 (copy)
  Stream #1:9 -> #0:9 (copy)
Press [q] to stop, [?] for help
[libopus @ 000001d244d68180] Invalid channel layout 5.1(side) for specified mapping family -1.
[aost#0:7/libopus @ 000001d244fca540] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[libopus @ 000001d2446ccfc0] 1 frames left in the queue on closing
[libopus @ 000001d2446cd3c0] 1 frames left in the queue on closing
[libopus @ 000001d2446cdbc0] 1 frames left in the queue on closing
[libopus @ 000001d244d6a180] 1 frames left in the queue on closing
[libopus @ 000001d244d66980] 1 frames left in the queue on closing
[libopus @ 000001d244d67180] 1 frames left in the queue on closing
Conversion failed!
```

**Comment by DaGooseYT** [comment]
Send the entire log file. A small snippet doesn't show everything.

**Comment by krab** [comment]
> Send the entire log file. A small snippet doesn't show everything.

https://pastebin.com/raw/VgFwXpTC

It shows that FFmpeg can't downmix properly using libopus, however in staxrip uses opusenc which again uses libopus, and it works no issue, but staxrip uses temporary dst->flac files for that, opusenc accepts flac as input source.

**Comment by DaGooseYT** [comment]
```
[libopus @ 000001d244d68180] Invalid channel layout 5.1(side) for specified mapping family -1.
```

It's complaining about the 5.1(side) channel layout in the source audio streams. It appears this version of FFmpeg doesn't have automatic channel mapping for Opus. Do you absolutely have to use Opus or can you try it with another codec?

**Comment by krab** [comment]
> Do you absolutely have to use Opus or can you try it with another codec?

Yes, because I want to. Anyway, StaxRip works for now just fine, even tho StaxRip's GUI is a mess.
