### ISSUE TITLE
Software is flagged as malware

### ISSUE THREAD

**Issue by radonm** [DaGooseYT/EncodeGUI#16]
Here are some interesting results
https://www.virustotal.com/gui/file/4f7f0bca6b61cf463f2c145ff16bdb17b00b2199cae2809a7fb1492460adf564/detection
https://www.virustotal.com/gui/file/bdec5cce3c7150c1fee7f8d4620458e823810637ac4a6ddb62acef7726d8dcd0

Should users be concerned with that?

**Comment by DaGooseYT** [comment]
There is nothing interesting with those results. The antivirus tools (trapmine, bkav pro) that "found" risks are just as untrustworthy as EncodeGUI/FrameGUI. Wake me up when a name brand antivirus flags it.
If you can't trust the precompiled binaries then compile yourself.
