### ISSUE TITLE
NCNN error after updating to 1.0.1

### ISSUE THREAD

**Issue by eltiel** [DaGooseYT/EncodeGUI#2]
I seem to be getting this error no matter what I do after updating to 1.0.1:

![image](https://user-images.githubusercontent.com/11868456/159979944-4aa3fa1c-7f23-488d-aed9-89dc2694d651.png)

Even when no filters have NCNN selected (as far as I can tell). I tried rolling back my GPU drivers and it's the same. I wanted to try rolling back to EncodeGUI 1.0.0 but realised I can't because it's no longer available for download. Would you be able to make available the older versions so that we can do a rollback if something like this happens?

**Comment by DaGooseYT** [comment]
You'll need to uninstall EncodeGUI completely before installing v1.0.1

Due to a license incompatibility with one of the dependencies, v1.0.0 has been taken down permanently.

**Comment by eltiel** [comment]
> You'll need to uninstall EncodeGUI completely before installing v1.0.1
> 
> Due to a license incompatibility with one of the dependencies, v1.0.0 has been taken down permanently.

You're right - a complete reinstallation fixed the issue. Thanks!
