### ISSUE TITLE
Won’t launch the app

### ISSUE THREAD

**Issue by SaberAkiyama** [DaGooseYT/EncodeGUI#3]
I tried to launch this app, but there was an error, causing “The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll.”

I tried the other method to fix this error, but it won’t work.

By the way, I use Windows 7 Home Premium (64-bit).

Here is a screenshot:

![Capture3](https://user-images.githubusercontent.com/48464326/163292603-c43ef4eb-3eea-4a02-92ad-0d3ad1dcf9cf.PNG)

**Comment by DaGooseYT** [comment]
Windows 7 is not supported. Use Windows 10 or newer.

See the docs for more info:
https://encodegui.com/docs/requirements.html
