### ISSUE TITLE
Can you please make it so that it will work on devices without GPU also ??

### ISSUE THREAD

**Issue by AdithyanNellickal** [DaGooseYT/EncodeGUI#5]
The title explains it all..

**Comment by DaGooseYT** [comment]
EncodeGUI was never designed for server or remote use. 
Half of the features would have to be disabled in order to prevent issues.

**Comment by AdithyanNellickal** [comment]
@DaGooseYT oh..

**Comment by AdithyanNellickal** [comment]
Btw it's not for server, it's for my PC. I have i9 9900k processor, but I don't own a GPU (currently a little bit unstable financially). That's why I was asking.
